#!/bin/sh

if ! mount | grep -q "/etc/profile"; then
    mount -o bind /mnt/SDCARD/sprig/etc/profile /etc/profile
fi

if [ ! -e /tmp/logs_rotated ]; then
    . /mnt/SDCARD/sprig/helperFunctions.sh
    rotate_logs
    log_message "sprigUI has entered the chat"
    touch /tmp/logs_rotated
fi

# stop pyui real time message writer if left open.
if [ -e /proc/$$/fd/3 ]; then
    echo "EXIT_APP" >&3
    exec 3>&-
fi

if ! pgrep adbd >/dev/null 2>&1; then
    /mnt/SDCARD/sprig/scripts/start_adbd.sh
fi

if ! pgrep dropbearmulti >/dev/null 2>&1; then
    /mnt/SDCARD/sprig/scripts/start_dropbear.sh
fi

if ! pgrep -f "/mnt/SDCARD/sprig/scripts/button_watchdog.sh" >/dev/null; then
    /mnt/SDCARD/sprig/scripts/button_watchdog.sh &
fi

if ! pgrep -f "/mnt/SDCARD/sprig/scripts/lid_watchdog.sh" >/dev/null; then
    /mnt/SDCARD/sprig/scripts/lid_watchdog.sh &
fi

# auto resume last app or game
if [ -e /mnt/SDCARD/sprig/flags/lastgame.lock ]; then
    ./freemma
    mv /mnt/SDCARD/sprig/flags/lastgame.lock /tmp/cmd_to_run.sh
    /tmp/cmd_to_run.sh
fi


# Fix timezone (why did Miyoo make this a /tmp file symlink?)
timezone=$(jq -r '.timezone // empty' "/mnt/SDCARD/Saves/mini-flip-system.json")

if [ -n "$timezone" ] && [ "$timezone" != "null" ]; then
    target="/mnt/SDCARD/miyoo285/zoneinfo/$timezone"

    # Check if /tmp/localtime already points to the correct target
    if [ "$(readlink -f /tmp/localtime)" = "$target" ]; then
        log_message "/tmp/localtime is already linked to $timezone"
    else
        log_message "Updating /tmp/localtime to $timezone"
        rm -f /tmp/localtime
        ln -s "$target" /tmp/localtime
        exit 0
    fi
fi


./freemma
/mnt/SDCARD/App/PyUI/launch.sh
