#!/bin/sh

mount -o bind /mnt/SDCARD/sprig/etc/profile /etc/profile

if ! pgrep adbd >/dev/null 2>&1; then
    /mnt/SDCARD/App/adbd_wifi/launch.sh
fi

if ! pgrep dropbearmulti >/dev/null 2>&1; then
    /mnt/SDCARD/App/SSH/launch.sh
fi

if ! pgrep -f "/mnt/SDCARD/sprig/scripts/powerbutton_watchdog.sh" >/dev/null; then
    /mnt/SDCARD/sprig/scripts/powerbutton_watchdog.sh &
fi

if [ -e /mnt/SDCARD/sprig/flags/lastgame.lock ]; then
    ./freemma
    mv /mnt/SDCARD/sprig/flags/lastgame.lock /tmp/cmd_to_run.sh
    /tmp/cmd_to_run.sh
fi

./freemma
/mnt/SDCARD/App/PyUI/launch.sh
