#!/bin/sh

. /mnt/SDCARD/sprig/helperFunctions.sh

set_performance

if ! mount | grep -q "/etc/profile"; then
    mount -o bind /mnt/SDCARD/sprig/etc/profile /etc/profile
    mount -o bind /mnt/SDCARD/sprig/etc/passwd /etc/passwd
    mount -o bind /mnt/SDCARD/sprig/etc/group /etc/group
fi

if [ ! -e /tmp/logs_rotated ]; then
    rotate_logs
    log_message "sprigUI has entered the chat"
    touch /tmp/logs_rotated
    init_volume_backlight
    log_message "Volume and backlight set to last known values."
fi

# stop pyui real time message writer if left open.
if [ -e /proc/$$/fd/3 ]; then
    echo "EXIT_APP" >&3
    exec 3>&-
fi

# Start network services if necessary
ADB_ENABLED="$(get_config_value '.menuOptions."Network Settings".enableADB.selected' "True")"
SSH_ENABLED="$(get_config_value '.menuOptions."Network Settings".enableSSH.selected' "False")"
SMB_ENABLED="$(get_config_value '.menuOptions."Network Settings".enableSMB.selected' "False")"

if [ "$ADB_ENABLED" = "True" ] && ! pgrep adbd >/dev/null 2>&1; then
    /mnt/SDCARD/sprig/scripts/start_adbd.sh
    log_message "Started ADBD"
fi
if [ "$SSH_ENABLED" = "True" ] && ! pgrep dropbearmulti >/dev/null 2>&1; then
    /mnt/SDCARD/sprig/scripts/start_dropbear.sh
    log_message "Started Dropbear"
fi
if [ "$SMB_ENABLED" = "True" ] && ! pgrep smbd >/dev/null 2>&1; then
    /mnt/SDCARD/sprig/scripts/start_samba.sh
    log_message "started Samba"
fi

# Start lid and button watchdogs
if ! pgrep -f "/mnt/SDCARD/sprig/scripts/button_watchdog.sh" >/dev/null; then
    /mnt/SDCARD/sprig/scripts/button_watchdog.sh &
fi
if ! pgrep -f "/mnt/SDCARD/sprig/scripts/lid_watchdog.sh" >/dev/null; then
    /mnt/SDCARD/sprig/scripts/lid_watchdog.sh &
fi

# auto resume last app or game
if [ -e /mnt/SDCARD/sprig/flags/lastgame.lock ]; then
    ./freemma
    mv /mnt/SDCARD/sprig/flags/lastgame.lock /tmp/cmd_to_run.sh
    /tmp/cmd_to_run.sh
fi

# Fix timezone (why did Miyoo make this a /tmp file symlink?)
timezone=$(jq -r '.timezone // empty' "/mnt/SDCARD/Saves/mini-flip-system.json")

if [ -n "$timezone" ] && [ "$timezone" != "null" ]; then
    target="/mnt/SDCARD/miyoo285/zoneinfo/$timezone"

    # Check if /tmp/localtime already points to the correct target
    if [ "$(readlink -f /tmp/localtime)" = "$target" ]; then
        log_message "/tmp/localtime is already linked to $timezone"
    else
        log_message "Updating /tmp/localtime to $timezone"
        rm -f /tmp/localtime
        ln -s "$target" /tmp/localtime
        exit 0
    fi
fi

# Actually launch the UI
./freemma
/mnt/SDCARD/App/PyUI/launch.sh
