#!/bin/sh

# This is sprigUI's entry point for taking over operation from the Miyoo Mini family device.
# This script gets executed by /customer/main.


##########     AT TIME OF BOOT     ##########

. /mnt/SDCARD/sprig/scripts/helperFunctions.sh

# auto shutdown if device powers on while lid is shut and plugged in
CHARGING="$(get_charging_state)"
LID="$(get_lid_state)"
if [ "$CHARGING" -ne 0 ] && [ "$LID" -eq 0 ]; then
    poweroff
fi

set_performance

touch /mnt/SDCARD/sprig/bin/MainUI
mount -o bind /mnt/SDCARD/sprig/bin/python /mnt/SDCARD/sprig/bin/MainUI
mount -o bind /mnt/SDCARD/sprig/etc/profile /etc/profile
mount -o bind /mnt/SDCARD/sprig/etc/passwd /etc/passwd
mount -o bind /mnt/SDCARD/sprig/etc/group /etc/group

# better to bind than to include 3 copies of all our libs
mkdir -p /mnt/SDCARD/miyoo/lib
mkdir -p /mnt/SDCARD/miyoo354/lib
mount -o bind /mnt/SDCARD/miyoo285/lib /mnt/SDCARD/miyoo/lib
mount -o bind /mnt/SDCARD/miyoo285/lib /mnt/SDCARD/miyoo354/lib

rotate_logs && log_message "sprigUI has entered the chat"

/mnt/SDCARD/sprig/scripts/importRAC.sh

# set up auto resume for last app or game
if [ -e /mnt/SDCARD/sprig/flags/lastgame.lock ]; then
    DISABLE_WIFI="$(get_config_value '.menuOptions."Lid and Power Settings".disableWifiInGame.selected' "False")"
    WIFI_ENABLED="$(get_pyui_config_value '.wifi' 1)"
    if [ "$DISABLE_WIFI" = "False" ] && [ "$WIFI_ENABLED" -eq 1 ]; then
        /mnt/SDCARD/sprig/scripts/network/start_wifi.sh
    fi
    freemma
    mv /mnt/SDCARD/sprig/flags/lastgame.lock /tmp/cmd_to_run.sh
fi

/mnt/SDCARD/sprig/scripts/theme_unpacker.sh

##########     MAIN OPERATION LOOP     ##########

while true; do

    # Start and stop network services as configured.
    /mnt/SDCARD/sprig/scripts/network/start_stop_services.sh &

    # Start battery, lid, and button watchdogs only if necessary.
    for thing in battery lid button; do
        if ! pgrep -f "/mnt/SDCARD/sprig/scripts/${thing}_watchdog.sh" >/dev/null; then
            /mnt/SDCARD/sprig/scripts/${thing}_watchdog.sh &
        fi
    done

    # Run any selected game or app.
    if [ -e /tmp/cmd_to_run.sh ]; then
        freemma
        chmod 777 /tmp/cmd_to_run.sh
        /tmp/cmd_to_run.sh
        rm /tmp/cmd_to_run.sh
    fi
        
    # Stop PyUI real time message writer if left open.
    kill_pyui_message_writer

    /mnt/SDCARD/sprig/scripts/audio_server.sh

    # Restart PyUI.
    has_v4_screen && fbset -g 752 560 752 560 32
    freemma
    /mnt/SDCARD/App/PyUI/launch.sh
done